### ISSUE TITLE
variantSet lookfiles appear on instances in Katana

### ISSUE THREAD

**Issue by ainaerco** [PixarAnimationStudios/OpenUSD#907]
### Description of Issue
How to get variantSet lookfiles appear on instance sources in Katana? It seems variants are authored on masters but variant attributes only appear on instances
[usd_instances.zip](https://github.com/PixarAnimationStudios/USD/files/3407463/usd_instances.zip)

### Steps to Reproduce
1. Start Katana.
2. Create PxrUsdIn node.
3. Add lookfile to usdExtraAttributesOrNamespaces.
4. Load instance_variants.usda from archive.
5. Switch instance mode to as sources and instances.
6. Lookfile will appear on instance instead of instance source.

### System Information (OS, Hardware)
Linux

### Package Versions
USD v19.07, Katana 3.0v9

**Comment by stevelavietes** [comment]
Attributes present on instanceable=true reference scopes in USD are intended to be applied to the instances (and can vary per-instance across the same master). So the behavior you're seeing with PxrUsdIn is expected.

However, a lookfile binding in katana is meaningful only if the locations it addresses are present in the scene below -- which is not true for an "instance" location. So I understand why you'd want that to be applied on the master location.

When in "as sources and instances" mode, PxrUsdIn has to analyze the instances in advance in order to organize the masters in a stable and human-readable form. Even if PxrUsdIn had an option to say, "add these attrs to the masters instead of the instance locations", that master organization code would need to handle the possibility of different values for an attribute across multiple instances which reference the same master. While technically possible, it would add considerable complexity to the resulting naming scheme (which already has to take things like combinations of variant set selections into account).

The simplest solution would be to introduce another scope beneath your instanceable references. If the lookfiles are authored and bound there (instead of on the root of the instance), everything would align within the master itself.

**Comment by jtran56** [comment]
Filed as internal issue USD-5456.

**Comment by sunyab** [comment]
Closing out old issue related to the retired usdKatana plugin.
