### ISSUE TITLE
[UsdKatana] Scope of arbitrary attributes from the point instancer are hardcoded to primitive

### ISSUE THREAD

**Issue by sirpalee** [PixarAnimationStudios/OpenUSD#908]
### Description of Issue
At this moment, pxrUsdIn hardcodes the scope of the arbitrary attributes to primitive on the instancer array. This is forcing renderer plugins to apply the data to each instance, potentially blowing up memory usage. We saw this behavior in Katana to Arnold.

I can think of two potential approaches:
- Set the scope up properly, and let expect the renderer plugin in Katana to deal with the scoping of the arbitrary attributes. Katana to Arnold already handles this case and I think Prman for Katana requires changes. I'm not sure about 3delight and v-ray.
- Add a USD specific attribute the arbitrary attribute, and let the renderer plugins handle it. This won't break existing behavior and requires minimal changes to renderer plugins.

Note: the katana developer guide is not specifying how the instancer array location arbitrary attributes are interpreted based on their scope.

### Steps to Reproduce
1. Import any point instancer with vertex/point scoped primvar via pxrUsdIn.
2. Inspect the geometry.arbitrary location on the generated instancer array.

### Package Versions
Latest dev

**Comment by jtran56** [comment]
Filed as internal issue #USD-5451.

**Comment by emeroo** [comment]
Hello, thanks for bringing this to our attention.

It's true that primvars on the instance array are hard-coded to be constant ("primitive") so that Prman for Katana can slice out the value for instance N and use the other fields as-is. That is to say, in order for Rfk instances to use per-instance primvars, the type of the primvar needs to be switched from non-constant to constant (because RfK doesn't do that itself).

There was a recent change to move only non-constant (type != "primitive") primvars down to the instance array (and leave the others untouched, on the point instancer). Are there cases where a primvar authored on the point instancer would be non-constant but _not_ intended for each instance in the array?

I ask because, if we modify the slicing behavior in RfK to do the non-constant -> constant type change, it's good to know about edge cases where this type change should _not_ occur. Do you know how KtoA handles this?

(Alternately, as you suggested, there could be an extra attribute to help direct the renderer plugins, but I am still curious about any specific cases.)

**Comment by sunyab** [comment]
Closing out old issue related to the retired usdKatana plugin.
